project:
  type: website
  output-dir: docs

website:
  title: "Emily Marple {{< fa brands bluesky >}}"
  favicon: media/favicon.png 
  navbar: 
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About me
      - href: field-notes.qmd
        text: Field Notes
  page-footer: 
    background: light
    left: Copyright 2026, Emily Marple
    right: This website is built with {{< fa heart title="a heart" >}}, [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/emilymarple/emilymarple.github.io){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}

format:
  html: 
    theme:
      - pulse
      - brand
    css: styles.css
    toc: true
    page-layout: full



