---
title: "How much is a queen worth?"
description: "An entomologist's dilemma"
author:
  - name: Emily Marple 
    url: https://emilymarple.github.io/
    orcid: 0009-0003-1651-7514
    affiliation: RaMP-UP Fellow and GSS Scholar at the Smithsonian Tropical Research Institute
date: 01-16-2026
categories: [work, personal, goals]
citation:
  url: https://emilymarple.github.io/posts/2025-01/16-a-queen&#39;s-worth
draft: true
---


Whack. Whack. Whack. 

“Que estás haciendo?”  pregunta el conserje. 

I look up at the shadow standing over me, backlit by the sun. “Oh--hola. Es un comejen de las termitas. Estaba en el… freezer? Y ahora yo necesito mezclarlas para contarlas," I say, stumbling through my Spanish.

Does what I’m doing make sense in any language?

I’m kneeling outside of the loading dock on a tarp, gripping a bright yellow hammer, sweat dripping as the sun presses down, relentless in this constant summer heat and humidity. Fragments of termite nest and bodies cling to my shirt and hair.

“Que cool!” he says, before heading inside. 

I continue hammering. Termite nests are deceptively strong. The outside falls away easily, crumbling in my fingers. But closer to the center, the nest thickens and hardens. It is almost like breaking apart an odd shaped piece of wood, reconstructed through termite feces and spit. 

Whack. Another piece breaks off. I sort carefully through the fragments until I find her: the queen.


Termite queens are the longest living insects in the entire world. They live to at least 25 years. Some species make it to 50. And it’s possible that they could live up to 100 years. Hidden deep within the nest, they are nearly impossible to study under natural conditions. 

I turn her gently in my fingers, inspecting her tiny head. Her white, pudgy body envelops her--an organism entirely specialized for reproduction. She depends on workers for feeding and grooming, and is fiercely protected by the soldiers. Both get nothing in return. Evolved over thousands of years, together the colony functions as a tightly coordinated system.

And now that system has been disrupted.

The nest was collected, frozen, and brought here for analysis. My role is to process it-- to measure, mix, and count. It's meticulous, repetitive work. Under a light, I use tweezers to separate the workers and soldiers from the nest, recording their numbers one by one. 

I sigh. 

How old is she? 10? 25, 50 years? 100? I haven’t even made it to 23 yet, and I feel like I’ve lived several lifetimes. 

Moments like this can feel contradictory. One one hand, the work requires distance and precision. On the other, spending so much time observing these organisms makes it difficult not to feel some connection to them. 

A mentor once told me, “If you like bugs, don’t become an entomologist. All you do is kill them.” I laughed at the time. I understand the tension now. 

But I also understand why the work matter. Termites play a critical role in decomposition and carbon cycling, shaping the ecosystems they inhabit. Studying their colonies helps us better understand these processes and the forces that drive them, especially in rapidly changing environments. 

My time here has pushed me to think more carefully about the relationship between scientific inquiry and the systems we study. It's not about eliminating that discomfort-- it's about being accountable to it, and ensuring the work ultimately contributes to a deeper understanding of the ecosystems we aim to protect.

I expect to continue encountering these tensions as I grow in this field. What matters to me is learning how to navigate them thoughtfully, without losing sight of the purpose behind the research.

With abundant love,
Emily

---

---
